export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Palestine"
];

export const roles = [
  "CEO / Founder",
  "Marketing Manager",
  "Business Analyst",
  "Sales Manager",
  "Research Analyst",
  "Other"
];

export const faqData = [
  {
    title: "1. Where does your data come from? ",
    description:
      "Our reports pull from a variety of publicly accessible and verified sources, such as government databases, regulatory publications, trade statistics, company disclosures, and reputable industry materials. You can trace all major data points back to the sources we cite.",
  },
  {
    title: "2. Are your reports generated by AI?",
    description:
      "We do utilize AI-powered tools to help structure, standardize, and organize data more efficiently. However, our research process includes validation checks and analytical reviews to ensure everything is clear, accurate, and contextually relevant.",
  },
  {
    title: "3. How often are reports updated?",
    description:
      "We periodically review our reports to include significant market developments, updated trade data, and any regulatory changes. You’ll find the date of the latest update noted on each report page.",
  },
  {
    title: "4. Can I see a sample before purchasing?",
    description:
      "Absolutely! Each report page features overview sections and sample previews, allowing you to assess the content before deciding to purchase the full version",
  },
  {
    title: "5. Do you provide custom research?",
    description:
      "Yes, we can offer custom research depending on your specific needs and requirements. Feel free to reach out to us with your requests for evaluation.",
  },
  {
    title: "6. How reliable are your forecasts?",
    description:
      "Our forecasts are crafted using structured modeling techniques, historical trend analysis, and assessments of market correlations. While these projections are based on data, they can still be influenced by broader economic and regulatory changes.",
  },
];

export const recentActivity = [
  'Report published: "India Nutra Market" (Today)',
  'Price updated: "Vitamin C Market" (Yesterday)',
  'Draft saved: "Germany Pharma" (2 days ago)',
  'Report published: "India Nutra Market" (Today)',
  'Price updated: "Vitamin C Market" (Yesterday)',
  'Draft saved: "Germany Pharma" (2 days ago)'
];

export const warningData = [
  'Drafts older than 14 days: 6',
  'Missing section PDF files: 2 reports',
  'Published reports without preview: 5',
  'Drafts older than 14 days: 6',
  'Missing section PDF files: 2 reports',
  'Published reports without preview: 5'
];

export const curatedData = [
  'New Product Launch',
  'Market Entry',
  'Competitor Analysis',
  'Pricing Strategy',
  'Investor/Board Presentation'
];

export const howThisHelpsYou = [
  'Validate New Product',
  'Compare Competitors',
  'Understand Pricing',
  'Reduce Market Entry Risk'
];

export const textContainerData = [
  'Explore Reports',
  'View Pricing',
  'Explore Trends',
  'Todays Offer',
  'Trending News',
  'Buyers Favourite',
  'Best Ingredients'
];

export const dataSource = [
  'Government trade databases and customs data',
  'Regulatory authority publicationst',
  'Industry associations and market bodies',
  'Company annual reports and disclosures',
  'Public financial statements',
  'Import export statistics',
  'Industry journals and credible publications'
];

export const marketEstimation = [
  'Top-down analysis (industry-level data allocation)',
  'Bottom-up estimation (aggregation of company and trade data)',
  'Trade-adjusted consumption modeling',
  'Historical trend extrapolation',
  'Comparative regional benchmarking'
];

export const forecastingMethodology = [
  'Historical growth trend analysis',
  'CAGR-based modeling',
  'Demand-driver correlation analysis',
  'Scenario-based outlook assessment',
  'Sensitivity checks for major influencing factors'
];

export const competitiveAnalysis = [
  'Publicly available company disclosures',
  'Product portfolio analysis',
  'Geographic presence mapping',
  'Strategic announcements and expansion activities',
  'Market positioning evaluation'
];

export const pricing_Trade = [
  'Trade data trends',
  'Public procurement references',
  'Market comparisons across regions',
  'Value-chain positioning analysis'
];

export const technology_Enabled = [
  'Extracting relevant information from diverse data sources',
  'Standardizing datasets into structured formats',
  'Improving content readability and presentation',
  'Maintaining citation traceability',
  'Reducing formatting inconsistencies'
];
